//
//  FroccsListInteractor.swift
//  Froccs
//
//  Created by Zsolt Pete on 2020. 05. 03..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

typealias FroccsListResponse = Result<[Froccs], Error>

final class FroccsListInteractor {
}

// MARK: - Extensions -

extension FroccsListInteractor: FroccsListInteractorInterface {
    
    func getFroccss(completition: (FroccsListResponse) -> Void) {
        var array = [Froccs]()
        array.append(contentsOf: FroccsManager.shared.getFrocsss())
        
        let result = FroccsListResponse.success(array)
        completition(result)
    }
    
}
