//
//  FroccsDetailWireframe.swift
//  Froccs
//
//  Created by Zsolt Pete on 2020. 05. 03..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FroccsDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(_ froccs: Froccs?) {
        let moduleViewController = FroccsDetailViewController()
        super.init(viewController: moduleViewController)

        let interactor = FroccsDetailInteractor()
        let presenter = FroccsDetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self, froccs: froccs)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension FroccsDetailWireframe: FroccsDetailWireframeInterface {
}
