//
//  FroccsDetailInteractor.swift
//  Froccs
//
//  Created by Zsolt Pete on 2020. 05. 03..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FroccsDetailInteractor {
}

// MARK: - Extensions -

extension FroccsDetailInteractor: FroccsDetailInteractorInterface {
}
