//
//  FroccsDetailInterfaces.swift
//  Froccs
//
//  Created by Zsolt Pete on 2020. 05. 03..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FroccsDetailWireframeInterface: WireframeInterface {
}

protocol FroccsDetailViewInterface: ViewInterface {
    func setWineSlider(to wine: Int?)
    func setWaterSlider(to water: Int?)
    func setTitleLabel(_ title: String?)
    func setDescription(_ desc: String?)
    func setWineCoounter(to water: Int?)
    func setWaterCoounter(to water: Int?)
}

protocol FroccsDetailPresenterInterface: PresenterInterface {
    func wineSliderChanged(_ value: Int)
    func waterSliderChanged(_ value: Int)
}

protocol FroccsDetailInteractorInterface: InteractorInterface {
}
