//
//  TabbarViewController.swift
//  citychat
//
//  Created by Levente Vig on 2019. 07. 12..
//  Copyright (c) 2019. CodeYard. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TabbarViewController: UITabBarController {

    // MARK: - Public properties -

    var presenter: TabbarPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        tabBar.tintColor = .yellow
        tabBar.unselectedItemTintColor = .black
        delegate = self
        presenter.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension TabbarViewController: TabbarViewInterface {
    
    func setTitle(_ title: String) {
        
    }
    
    func select(tab: Int) {
        selectedIndex = tab
    }
    
    func set(controllers: [UIViewController]) {
        viewControllers = controllers
        viewControllers?.forEach({ controller in
            if let controller = controller as? BaseTabbarProtocolController {
                controller.setTabbarItem()
            }
        })
    }
}

extension TabbarViewController: UITabBarControllerDelegate {
    func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {
        return true
    }
}
